drop table                                                                      
gards_auto_sample_cat                                                           
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_rlr_ssreb                                                                 
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_rlr_objective                                                             
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_data_log                                                                  
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_qc_results                                                                
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_roi_counts                                                                
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_fpe                                                                       
cascade constraints ;                                                           
                                                                                
drop table                                                                      
rms_purge_samples                                                               
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_soh_num_data                                                              
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_bg_roi_counts                                                             
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_b_resolution_pairs_orig                                                   
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_receipt_log                                                               
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_energy_cal                                                                
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_total_effic                                                               
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_sample_update_params                                                      
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_nucl_lines_ided_orig                                                      
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_nucl_ided_orig                                                            
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_met_data                                                                  
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_sample_data                                                               
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_bg_std_spectra                                                            
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_nucl_ided                                                                 
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_qchistory                                                                 
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_interval                                                                  
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_energy_pairs_orig                                                         
cascade constraints ;                                                           
                                                                                
drop table                                                                      
rms_purge_diffs                                                                 
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_histogram                                                                 
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_bg_energy_cal                                                             
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_bg_proc_params                                                            
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_sample_cert_lines                                                         
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_resolution_cal_cov                                                        
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_efficiency_cal                                                            
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_soh_char_data                                                             
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_notify                                                                    
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_soh_header                                                                
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_roi_limits                                                                
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_flags                                                                     
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_rlr                                                                       
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_query_results                                                             
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_nucl_lines_ided                                                           
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_resolution_cal_orig                                                       
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_resolution_pairs                                                          
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_peaks                                                                     
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_nic                                                                       
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_comments                                                                  
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_trendvue                                                                  
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_rlr_conclusions                                                           
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_sample_flags                                                              
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_bg_roi_concs                                                              
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_sample_ratios                                                             
cascade constraints ;                                                           
                                                                                
drop table                                                                      
gards_sample_proc_params                                                        
cascade constraints ;                                                           
                                                                                
SQL> SPOOL OFF
